using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace EcsEngine.SourceGen;

/// <summary>
/// Incremental source generator that produces component type metadata registrations
/// for every <c>IEcsComponent</c> struct visible in the consuming compilation.
/// Detects <c>[ArchetypeStorage]</c> attributes at compile time and generates
/// a static initializer that pre-populates ComponentTypeRegistry without runtime reflection.
/// </summary>
[Generator]
public sealed class ComponentRegistryGenerator : IIncrementalGenerator
{
    private const string IEcsComponentFqn = "EcsEngine.Core.IEcsComponent";
    private const string ArchetypeStorageAttrFqn = "EcsEngine.Core.ArchetypeStorageAttribute";
    private const string CoreAssemblyName = "EcsEngine.Core";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Collect every struct / record-struct declaration that has a base-list
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is StructDeclarationSyntax { BaseList: not null } ||
                    node is RecordDeclarationSyntax { BaseList: not null },
                transform: static (ctx, _) =>
                    ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol)
            .Where(static t => t is not null)
            .Select(static (t, _) => t!);

        context.RegisterSourceOutput(
            context.CompilationProvider.Combine(candidates.Collect()),
            static (spc, pair) =>
            {
                // Only generate in EcsEngine.Core to avoid duplication
                if (pair.Left.AssemblyName != CoreAssemblyName)
                    return;
                Execute(spc, pair.Right);
            });
    }

    private static void Execute(
        SourceProductionContext spc,
        ImmutableArray<INamedTypeSymbol> rawCandidates)
    {
        var components = new List<(INamedTypeSymbol Type, bool HasArchetypeAttr, int ChunkSizeBytes)>();

        foreach (INamedTypeSymbol type in rawCandidates)
        {
            if (!type.IsValueType || type.IsAbstract || type.IsGenericType) continue;

            // Simple check: does it implement IEcsComponent?
            bool isEcsComponent = false;
            foreach (INamedTypeSymbol iface in type.AllInterfaces)
            {
                if (iface.Name == "IEcsComponent" && iface.ContainingNamespace.Name == "Core")
                {
                    isEcsComponent = true;
                    break;
                }
            }
            if (!isEcsComponent) continue;
            if (IsInaccessible(type)) continue;

            // Detect [ArchetypeStorage] attribute and extract ChunkSizeBytes if present.
            bool hasArchetypeAttr = false;
            int chunkSizeBytes = 16384; // Default from ArchetypeStorageAttribute.DefaultChunkSizeBytes

            foreach (AttributeData attr in type.GetAttributes())
            {
                if (attr.AttributeClass?.Name == "ArchetypeStorageAttribute")
                {
                    hasArchetypeAttr = true;
                    // Extract ChunkSizeBytes named argument if present.
                    foreach (KeyValuePair<string, TypedConstant> named in attr.NamedArguments)
                    {
                        if (named.Key == "ChunkSizeBytes" && named.Value.Value is int cSize)
                        {
                            chunkSizeBytes = cSize;
                            break;
                        }
                    }
                    break;
                }
            }

            components.Add((type, hasArchetypeAttr, chunkSizeBytes));
        }

        if (components.Count == 0) return;

        var sb = new StringBuilder();
        BuildSource(sb, components);
        spc.AddSource("ComponentRegistry.g.cs", sb.ToString());
    }

    private static bool IsInaccessible(INamedTypeSymbol type)
    {
        ISymbol? current = type;
        while (current is INamedTypeSymbol named)
        {
            var acc = named.DeclaredAccessibility;
            if (acc == Accessibility.Private ||
                acc == Accessibility.Protected ||
                acc == Accessibility.ProtectedAndInternal)
                return true;
            current = current.ContainingSymbol;
        }
        return false;
    }

    private static void BuildSource(
        StringBuilder sb,
        List<(INamedTypeSymbol Type, bool HasArchetypeAttr, int ChunkSizeBytes)> components)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace EcsEngine.SourceGen.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    internal static class __ComponentRegistryInit__");
        sb.AppendLine("    {");
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("        internal static void __Init__()");
        sb.AppendLine("        {");

        foreach (var (type, hasArchetypeAttr, chunkSizeBytes) in components)
        {
            string fqn = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string storageKind = hasArchetypeAttr
                ? "global::EcsEngine.Core.Storage.StorageKind.Archetype"
                : "global::EcsEngine.Core.Storage.StorageKind.Sparse";

            sb.AppendLine($"            {{");
            sb.AppendLine($"                var type = typeof({fqn});");
            sb.AppendLine($"                if (global::EcsEngine.Core.Storage.ComponentTypeRegistry._GeneratedRegistry.ContainsKey(type)) goto skip_{type.Name};");
            sb.AppendLine($"                int sizeBytes = global::System.Runtime.InteropServices.Marshal.SizeOf<{fqn}>();");
            sb.AppendLine($"                var info = new global::EcsEngine.Core.Storage.ComponentTypeInfo(");
            sb.AppendLine($"                    type,");
            sb.AppendLine($"                    {storageKind},");
            sb.AppendLine($"                    sizeBytes,");
            sb.AppendLine($"                    {chunkSizeBytes},");
            sb.AppendLine($"                    static capacity => new global::EcsEngine.Core.Storage.ComponentColumn<{fqn}>(capacity)");
            sb.AppendLine($"                );");
            sb.AppendLine($"                global::EcsEngine.Core.Storage.ComponentTypeRegistry._GeneratedRegistry[type] = info;");
            sb.AppendLine($"                skip_{type.Name}:;");
            sb.AppendLine($"            }}");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }
}


