using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace EcsEngine.SourceGen;

/// <summary>
/// Incremental source generator that produces <c>DeterministicHasher&lt;T&gt;</c>
/// implementations for every non-private <c>IEcsComponent</c> struct visible in
/// the consuming compilation.  A single <c>[ModuleInitializer]</c> registers all
/// implementations before any user code runs.
/// </summary>
[Generator]
public sealed class DeterministicHasherGenerator : IIncrementalGenerator
{
    private const string IEcsComponentFqn = "EcsEngine.Core.IEcsComponent";
    private const string HasherBaseFqn    = "EcsEngine.Core.DeterministicHasher";
    private const ulong  FnvOffset        = 14695981039346656037UL;
    private const ulong  FnvPrime         = 1099511628211UL;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Collect every struct / record-struct declaration that has a base-list
        // (i.e. implements at least one interface).
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is StructDeclarationSyntax { BaseList: not null } ||
                    node is RecordDeclarationSyntax { BaseList: not null },
                transform: static (ctx, _) =>
                    ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol)
            .Where(static t => t is not null)
            .Select(static (t, _) => t!);

        context.RegisterSourceOutput(
            context.CompilationProvider.Combine(candidates.Collect()),
            static (spc, pair) => Execute(spc, pair.Left, pair.Right));
    }

    // -------------------------------------------------------------------------

    private static void Execute(
        SourceProductionContext spc,
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol> rawCandidates)
    {
        INamedTypeSymbol? iEcsComponent = compilation.GetTypeByMetadataName(IEcsComponentFqn);
        if (iEcsComponent is null) return;

        // Only generate when DeterministicHasher<T> itself is present (Core is referenced).
        INamedTypeSymbol? hasherBase = compilation.GetTypeByMetadataName($"{HasherBaseFqn}`1");
        if (hasherBase is null) return;

        var components = new List<INamedTypeSymbol>();
        foreach (INamedTypeSymbol type in rawCandidates)
        {
            if (!type.IsValueType || type.IsAbstract || type.IsGenericType) continue;
            if (!ImplementsInterface(type, iEcsComponent)) continue;
            if (IsInaccessible(type)) continue;
            components.Add(type);
        }

        if (components.Count == 0) return;

        var sb = new StringBuilder();
        BuildSource(sb, components, iEcsComponent);
        spc.AddSource("DeterministicHashers.g.cs", sb.ToString());
    }

    // -------------------------------------------------------------------------
    // Helpers: symbol inspection

    private static bool ImplementsInterface(INamedTypeSymbol type, INamedTypeSymbol iface)
    {
        foreach (INamedTypeSymbol i in type.AllInterfaces)
            if (SymbolEqualityComparer.Default.Equals(i, iface)) return true;
        return false;
    }

    /// <summary>
    /// Returns true when the type (or any containing type) has accessibility
    /// that would prevent referencing it from generated code within the same assembly.
    /// </summary>
    private static bool IsInaccessible(INamedTypeSymbol type)
    {
        ISymbol? current = type;
        while (current is INamedTypeSymbol named)
        {
            var acc = named.DeclaredAccessibility;
            if (acc == Accessibility.Private   ||
                acc == Accessibility.Protected ||
                acc == Accessibility.ProtectedAndInternal)
                return true;
            current = current.ContainingSymbol;
        }
        return false;
    }

    // -------------------------------------------------------------------------
    // Code generation

    private static void BuildSource(
        StringBuilder sb,
        List<INamedTypeSymbol> components,
        INamedTypeSymbol iEcsComponent)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace EcsEngine.SourceGen.Generated");
        sb.AppendLine("{");

        // One static class with a [ModuleInitializer] that wires up all hashers.
        sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("    internal static class __DeterministicHasherInit__");
        sb.AppendLine("    {");
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("        internal static void __Init__()");
        sb.AppendLine("        {");
        foreach (INamedTypeSymbol type in components)
        {
            string fqn = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string cls = HasherClassName(type);
            sb.AppendLine($"            global::{HasherBaseFqn}<{fqn}>.SetDefault(new {cls}());");
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // One concrete hasher class per component type.
        foreach (INamedTypeSymbol type in components)
        {
            string fqn = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string cls = HasherClassName(type);

            sb.AppendLine($"    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
            sb.AppendLine($"    internal sealed class {cls}");
            sb.AppendLine($"        : global::{HasherBaseFqn}<{fqn}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public override uint Hash(in {fqn} value)");
            sb.AppendLine("        {");
            sb.AppendLine($"            ulong h = {FnvOffset}UL;");

            List<(string Name, ITypeSymbol Type)> members = GetHashableMembers(type);
            foreach ((string name, ITypeSymbol memberType) in members)
            {
                string contrib = Contribution(memberType, $"value.{name}", iEcsComponent);
                sb.AppendLine($"            h = (h ^ ({contrib})) * {FnvPrime}UL;");
            }

            sb.AppendLine("            return (uint)(h ^ (h >> 32));");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.Append("}");
    }

    /// <summary>
    /// Returns the members that contribute to the hash.
    /// For record structs: auto-properties (those backed by a compiler field).
    /// For plain structs: non-private, non-implicit instance fields.
    /// </summary>
    private static List<(string Name, ITypeSymbol Type)> GetHashableMembers(INamedTypeSymbol type)
    {
        var result = new List<(string, ITypeSymbol)>();

        if (type.IsRecord)
        {
            foreach (ISymbol member in type.GetMembers())
            {
                if (member is not IPropertySymbol prop) continue;
                if (prop.IsStatic || prop.IsIndexer || prop.IsImplicitlyDeclared) continue;

                // Auto-properties have a compiler-generated backing field named <Prop>k__BackingField.
                // Computed properties do not — skip them.
                bool hasBacking = type.GetMembers($"<{prop.Name}>k__BackingField").Length > 0;
                if (hasBacking)
                    result.Add((prop.Name, prop.Type));
            }
        }
        else
        {
            foreach (ISymbol member in type.GetMembers())
            {
                if (member is not IFieldSymbol field) continue;
                if (field.IsStatic || field.IsImplicitlyDeclared) continue;
                if (field.DeclaredAccessibility == Accessibility.Private) continue;
                result.Add((field.Name, field.Type));
            }
        }

        return result;
    }

    /// <summary>Returns a C# expression of type <c>ulong</c> for one field contribution.</summary>
    private static string Contribution(ITypeSymbol type, string expr, INamedTypeSymbol iEcsComponent)
    {
        switch (type.SpecialType)
        {
            case SpecialType.System_Boolean:
                return $"({expr} ? 1UL : 0UL)";

            case SpecialType.System_Char:
            case SpecialType.System_Byte:
            case SpecialType.System_UInt16:
            case SpecialType.System_UInt32:
            case SpecialType.System_UInt64:
                return $"(ulong){expr}";

            case SpecialType.System_SByte:
            case SpecialType.System_Int16:
            case SpecialType.System_Int32:
            case SpecialType.System_Int64:
                // Cast via unchecked to avoid overflow exceptions for negative values.
                return $"unchecked((ulong){expr})";

            case SpecialType.System_Single:
                // Reinterpret float bits as int, zero-extend to ulong.
                return $"(ulong)(uint)global::System.BitConverter.SingleToInt32Bits({expr})";

            case SpecialType.System_Double:
                // Reinterpret double bits as long, then unchecked-cast to ulong.
                return $"unchecked((ulong)global::System.BitConverter.DoubleToInt64Bits({expr}))";

            default:
                // Nested IEcsComponent struct: delegate to its own DeterministicHasher.
                if (type.IsValueType && type is INamedTypeSymbol named &&
                    ImplementsInterface(named, iEcsComponent))
                {
                    string fqn = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    return $"(ulong)global::{HasherBaseFqn}<{fqn}>.Default.Hash(in {expr})";
                }

                // Unsupported field type: contribute zero so generation still succeeds.
                // The caller can register a manual hasher for types that need full coverage.
                return "0UL /* unsupported field type */";
        }
    }

    /// <summary>Produces a valid C# identifier for the generated hasher class.</summary>
    private static string HasherClassName(INamedTypeSymbol type)
    {
        string ns = type.ContainingNamespace.IsGlobalNamespace
            ? ""
            : type.ContainingNamespace.ToDisplayString().Replace('.', '_') + "_";

        // Include containing types for nested types.
        var names = new List<string>();
        INamedTypeSymbol? cur = type;
        while (cur is not null)
        {
            names.Insert(0, cur.Name);
            cur = cur.ContainingType;
        }

        return "__DH_" + ns + string.Join("_", names);
    }
}
